### ISSUE TITLE
nifti_wmql points to a non existing qry file

### ISSUE THREAD

**Issue by sbouix** [pnlbwh/pnlNipype#16]
nifti_wmql variable for the default query point to exec/wmql-2.0.qry, but it is in scripts/wmql-2.0.qry

**Comment by tashrifbillah** [comment]
nifti_wmql issue fixed by 98497622b48217ca7ebe93234b1660def3aa43b4

**Comment by tashrifbillah** [comment]
For `nifti_fs2dwi`, similar issue was reported in the use of `bse.py`. To solve that, `bse.py` has been replaced with `pjoin(FILEDIR,'bse.py')` so it uses `bse.py` script native to *pnlNipype*.

See e0847d3bc1c671fce47155f6df154ad85091e351
