### ISSUE TITLE
Typo in FSL eddy usage

### ISSUE THREAD

**Issue by monicalyons** [pnlbwh/pnlNipype#22]
In [FSL Eddy instructions](https://github.com/pnlbwh/pnlNipype/blob/master/TUTORIAL.md#ii-using-fsl-eddy) in tutorial:
acuisition --> acquisition

**Comment by tashrifbillah** [comment]
Fixed by https://github.com/pnlbwh/pnlNipype/commit/6393cf714b2b449238b34533f260d2f492300f3d
