### ISSUE TITLE
nifti_bse

### ISSUE THREAD

**Issue by kniajans** [pnlbwh/pnlNipype#23]
https://github.com/monicalyons/pnlNipype/blob/master/TUTORIAL.md#i-baseline-image

Doesn't add suffix "_bse.nii.gz" to the output file, despite saying it would.

**Comment by tashrifbillah** [comment]
Sorry, it says default is `inPrefix_bse.nii.gz` if `-o` is not provided. But it doesn't say if `-o` is provided, it will still add `_bse.nii.gz`.

The reason behind not adding `_bse.nii.gz` always, is to give the user freedom for naming it his way.
