### ISSUE TITLE
wmqlqc .vtp

### ISSUE THREAD

**Issue by kniajans** [pnlbwh/pnlNipype#32]
https://github.com/pnlbwh/pnlNipype/blob/master/scripts/wmqlqc.py

the script doesn't process .vtp files from Clustering output, would it be possible to include that? 
how should I format the input directory as a list, just by inputting the path?

**Comment by tashrifbillah** [comment]
> the script doesn't process .vtp files from Clustering output, would it be possible to include that?

I think that's unlikely. The purpose of this script is to make html files out of queried vtk files. The queried vtk files are obtained from [wmql.py](https://github.com/pnlbwh/pnlNipype/blob/master/docs/TUTORIAL.md#white-matter-query). On the other hand, I am not sure how do you want to feed .vtp files in it. May be you want to look at the [base package](https://github.com/SlicerDMRI/whitematteranalysis) to see if they have a way to do it.



> how should I format the input directory as a list, just by inputting the path?

https://github.com/pnlbwh/pnlNipype/blob/master/docs/TUTORIAL.md#render-white-matter-tracts

Hope the example helps.
