### ISSUE TITLE
pnl_epi output

### ISSUE THREAD

**Issue by kniajans** [pnlbwh/pnlNipype#35]
pnl_epi has come out with two mask outputs:
`CASE-dwi-epi.nii.gz-mask.nii.gz` and `CASE-dwi-epi.gz-mask.nii.gz`. From what I can tell, they're the same mask 
The bvals/bvecs are outputed in the following manner: `CASE-dwi-epi.nii.gz.bvec` , would it be possible to just have it outputed as `CASE-dwi-epi.bvec`?

**Comment by tashrifbillah** [comment]
That should not be right. It should give you only one mask.

I communicated to @mglyons how `-o` specification of `pnl_epi` has changed. Previously, it used to accept `-o niftiFile`. Now, it accepts `-o niftiPrefix`. Check `pnl_epi -h`.

Rest assured, if you delete what you have reported and do a fresh run with `-o niftiPrefix` (prefix doesn't contain .nii.gz or whatever), then you should get consistent output.

If it still happens, I can take a look at it.
