### ISSUE TITLE
nifti_fs hires flag

### ISSUE THREAD

**Issue by sbouix** [pnlbwh/pnlNipype#36]
Can we have the FreeSurfer script have the -hires flag from recon-all as an option and set it to "on" by default?

**Comment by tashrifbillah** [comment]
1. 
FreeSurfer --hires flag requires an expert options file.
https://surfer.nmr.mgh.harvard.edu/fswiki/SubmillimeterRecon

Should we provide one or take input for that?

2. 
Enabling the flag would introduce `-hires -expert expert_file.txt` in all of the `recon-all` commands [here](https://github.com/pnlbwh/pnlNipype/blob/master/scripts/fs.py#L116)

**Comment by tashrifbillah** [comment]
@tashrifbillah figured out the answers.

Fixed by PR #38
