### ISSUE TITLE
cannot import name 'UKFTractography' from 'plumbum.cmd'

### ISSUE THREAD

**Issue by njhunsak** [pnlbwh/pnlNipype#41]
Unable to run the ukf command:

```
(base)  $ ~/build/pnlNipype/exec/ukf --help
Traceback (most recent call last):
  File "/fslhome/intj5/build/pnlNipype/exec/ukf", line 6, in <module>
    from plumbum.cmd import UKFTractography
ImportError: cannot import name 'UKFTractography' from 'plumbum.cmd' (unknown location)
(base)  $ 
```

Not sure if UKFTractography needs to be one of these directories installed as part of your pipeline:

```
(base) $ ls -1 ~/apps/pnlbwh/pnlNipype/ 
ANTs
ANTs-build
dcm2niix
tract_querier-2019-05-08
tract_querier-d4a88aa
trainingDataT1AHCC-8141805
trainingDataT2Masks-12a14d9
ukftractography
UKFTractography-2019-05-01
UKFTractography-662c16f
UKFTractography-build
```

**Comment by tashrifbillah** [comment]
[The instruction](https://github.com/pnlbwh/pnlpipe#global-bashrc) has been part of our NRRD pipeline. It looks like we missed it in our new NIFTI pipeline.

For now, you should do:

> source UKFTractography-662c16f/env.sh

In the meantime, we shall include this instruction in our documentation.

**Comment by njhunsak** [comment]
I've confirmed that this works.
