### ISSUE TITLE
No files generated with fs2dwi

### ISSUE THREAD

**Issue by njhunsak** [pnlbwh/pnlNipype#43]
With or without the debug mode, no files are being generated in my output directory:

```bash
(base) bash-4.2$ ~/build/pnlNipype/exec/nifti_fs2dwi \
> --dwi dwi_epi.nii.gz \
> --dwimask dwi_epi-mask.nii.gz \
> --freesurfer /fslhome/intj5/compute/data/MAX-UCSD/freesurfer_subjects/sub-003/ \
> --debug \
> --outDir /fslhome/intj5/compute/data/tmp/sub-003/fs2dwi \
> direct
Making output directory
Making brain.nii.gz and wmparc.nii.gz from their mgz versions
Extracting B0 from DWI and masking it
Made masked B0
DWI resolution: [1. 1. 2.]
FreeSurfer brain resolution: [1. 1. 1.]
Resolution is not uniform among all the axes
(base) bash-4.2$ ls /fslhome/intj5/compute/data/tmp/sub-003/fs2dwi
(base) bash-4.2$ 
```

**Comment by tashrifbillah** [comment]
What does the following say?

```
cd pnlNipype
git log -3
```

**Comment by njhunsak** [comment]
```bash
(base) bash-4.2$ git log -3
commit 1ba2c42ca5ace071a8f67bbf2d61d6c344b39d4a
Author: Billah, Tashrif <tbillah@bwh.harvard.edu>
Date:   Tue Dec 10 10:31:04 2019 -0500

    look for antsRegistrationSyNMI in FILEDIR

commit d7cfc7c7aa36e5ffae5877d66ada04b6d8780c73
Author: Billah, Tashrif <tbillah@bwh.harvard.edu>
Date:   Mon Dec 9 22:10:16 2019 -0500

    use ANTSREG_THREADS instead of N_CPU for ants

commit 27be7800498afa9437f149920cdb69a5b5b64a42
Author: Billah, Tashrif <tbillah@bwh.harvard.edu>
Date:   Mon Dec 9 22:09:43 2019 -0500

    remove previous output
```

**Comment by tashrifbillah** [comment]
That's your error message:

> Resolution is not uniform among all the axes

Is the dwi resolution not uniform along all axes? The script is programmed to exist if it is not.

**Comment by tashrifbillah** [comment]
May be we had problem with antsRegistration about non uniform resolution along spatial axes, which is why it is there.

Would you like to comment out the checking and see how it goes?

```python
if dwi_res.ptp() or brain_res.ptp():
    print('Resolution is not uniform among all the axes')
    sys.exit(1)
```
Enclose the above block in triple (\```   \```) quotes.

**Comment by njhunsak** [comment]
The resolution of my DWI image is 0.94 x 0.94 x 2.00 and the resolution of my T1 image is 1.2 x 0.94 x 0.94. Should I resample my images to make them isotropic?

**Comment by tashrifbillah** [comment]
> The resolution of my DWI image is 0.94 x 0.94 x 2.00

Resampling is an option. But before, I would try disabling the above block and see how it goes.

> the resolution of my T1 image is 1.2 x 0.94 x 0.94

This should not be a problem given FreeSurfer produces `brain.mgz` with a uniform resolution typically 1mm^3. Later, `brain.mgz` is the one used, not T1.

**Comment by njhunsak** [comment]
> Enclose the above block in triple (\``` ```) quotes.

Commenting out the code with triple (""" """) quotes worked.

**Comment by tashrifbillah** [comment]
Okay. Can you superimpose `wmparcInDwi.nii.gz` upon `maskedbse.nii.gz` and evaluate the quality of registration?

**Comment by njhunsak** [comment]
Registration looks like this:

![snapshot0001](https://user-images.githubusercontent.com/4333838/70582507-bededc00-1b88-11ea-9b7c-ffe2db035e97.png)

Now I get the same error when I try to include the t2, is there another place in the code that I need to comment out?

**Comment by tashrifbillah** [comment]
Other block:

https://github.com/pnlbwh/pnlNipype/blob/master/scripts/fs2dwi.py#L264

**Comment by njhunsak** [comment]
Thanks. That all works now.

**Comment by tashrifbillah** [comment]
Centrally fixed by https://github.com/pnlbwh/pnlNipype/commit/c0012c108cdd195bb234f0960f1458ecae1c4dbe
