### ISSUE TITLE
Need access to nhdr program

### ISSUE THREAD

**Issue by njhunsak** [pnlbwh/pnlNipype#45]
Found out I needed access to `nhdr_write.py` found in the [conversion](https://github.com/pnlbwh/conversion) repository. You may want to add these programs to this repository. I've already downloaded and installed the programs from the other repository.

**Comment by tashrifbillah** [comment]
It was already [here](https://github.com/pnlbwh/pnlNipype/blob/master/requirements.txt#L11).

Did you not do [pip install -r requirements.txt](https://github.com/pnlbwh/pnlNipype#pnlpipe-software) ?

**Comment by njhunsak** [comment]
> Did you not do [pip install -r requirements.txt](https://github.com/pnlbwh/pnlNipype#pnlpipe-software) ?

I did. I wonder why I couldn't find it or run the program?

**Comment by tashrifbillah** [comment]
I may know why.

With `pip install`, package goes to your `~/miniconda3/lib/python3.6/site-packages/conversion/` directory. Then, modules from conversion can be imported with python `import` statement. But, the modules don't appear on your path to run as standalone executables. 

To be able to run one of them i.e. `nhdr_write.py --help` as a standalone executable, you need to download conversion separately or run as:

> python ~/miniconda3/lib/python3.6/site-packages/conversion/nhdr_write.py --help

Hope this helps. 

By the way, do you have a suggestion about where I should put the above explanation in my README/TUTORIAL?

**Comment by njhunsak** [comment]
I might stick it after line 168 in the README.txt file.

**Comment by sbouix** [comment]
I think these are important utility scripts, and we should consider soft links in the exec folder.

**Comment by tashrifbillah** [comment]
Fixed by https://github.com/pnlbwh/conversion/commit/deb01793a27b7e4b467c0d8ca81de005541ff122

Upon installation of conversion repository, the useful scripts `nhdr_write.py` and `nifti_write.py` are copied to python bin directory. The python bin directory i.e. the scripts are available on user PATH upon either of:
```python
source miniconda3/bin/activate
or 
conda activate pnlpipe3
```

Thus, the user is no longer required to look into many directories deep to find the scripts or clone conversion separately.
