### ISSUE TITLE
Free-water analysis

### ISSUE THREAD

**Issue by arched1** [pnlbwh/pnlNipype#51]
Hello! 

I was wondering if there were plans to add a github repository specifically for the free-water correction? 

Thanks!
Derek

**Comment by tashrifbillah** [comment]
Hi @oferpasternak,

Can you please answer this question?

**Comment by oferpasternak** [comment]
Hi Derek,
There are such plans down the road, but this is not yet available as part of pnlNipype.
Best,
Ofer

**Comment by arched1** [comment]
Hi @oferpasternak -- 

Sounds great. Are you aware of any existing repositories or open source code for single shell FW analysis? 

Thanks!
Derek

**Comment by tashrifbillah** [comment]
Issue marked as `stale` due to inactivity.

**Comment by tashrifbillah** [comment]
Answer `unknown`.
