### ISSUE TITLE
Broken link for mktrainingfiles.sh

### ISSUE THREAD

**Issue by eknyazhe** [pnlbwh/pnlNipype#55]
the link for `mktrainingfiles.sh` in TUTORIAL.md is broken

**Comment by tashrifbillah** [comment]
Currently, it is https://github.com/pnlbwh/trainingDataT1AHCC/blob/master/mktrainingfiles.sh

Correction required-- https://github.com/pnlbwh/trainingDataT1AHCC/blob/master/mktrainingcsv.sh

\**Pending\**
