### ISSUE TITLE
unring.py error

### ISSUE THREAD

**Issue by eknyazhe** [pnlbwh/pnlNipype#64]
Getting the following error when running `unring.py` on `/data/pnl/soft/pnlpipe3/bashrc3-centos6` on any case:

`(pnlpipe3) [ek520@rgs15 dwi]$ unring sub-1001_ses-01_desc-Xc_dwi.nii.gz sub-1001_ses-01_desc-XcUn_dwi.nii.gz`

```vim
Working directory /tmp/tmphng0_fzd
Traceback (most recent call last):
  File "/data/pnl/soft/pnlpipe3/pnlNipype/exec/unring", line 87, in <module>
    main()
  File "/data/pnl/soft/pnlpipe3/pnlNipype/exec/unring", line 58, in main
    pool= Pool(N_CPU)
UnboundLocalError: local variable 'N_CPU' referenced before assignment
```

**Comment by tashrifbillah** [comment]
Sorry about that, the error is strange. Can you do:

`unring.py <dwi> <outPrefix> <ncpu>`

While I take a look at it?
