### ISSUE TITLE
Small typo with documentation

### ISSUE THREAD

**Issue by sbouix** [pnlbwh/pnlNipype#65]
In the global bashrc description:

- [x] dcm2niix
`export PATH=~/dcm2niix/build/bin`
should be 
`export PATH=~/dcm2niix/build/bin:$PATH`

- [x] Also `/absolute/path/to/pnlNipype/exec` shoudl be added to `$PATH`

- [x] Also it might be worth making this more generic as the paths with "~" may not be where the software is installed in each setup.

```vim 
source ~/miniconda3/bin/activate                 # should intoduce '(base)' in front of each line
export FSLDIR=~/fsl                              # you may specify another directory where FreeSurfer is installed
export PATH=$PATH:$FSLDIR/bin
source $FSLDIR/etc/fslconf/fsl.sh
export FREESURFER_HOME=~/freesurfer              # you may specify another directory where FreeSurfer is installed
source $FREESURFER_HOME/SetUpFreeSurfer.sh
export $PATH=$PATH:/absolute/path/to/pnlNipype/scripts
export ANTSPATH=/path/to/ANTs/bin/
export PATH=$ANTSPATH:ANTs/Scripts:$PATH         # define ANTSPATH and export ANTs scripts in your path
export PATH=~/dcm2niix/build/bin
export PY2BIN=/absolute/path/to/miniconda2/bin   # for whitematteranalysis package
```

**Comment by tashrifbillah** [comment]
https://github.com/pnlbwh/pnlNipype#global-bashrc

**Comment by tashrifbillah** [comment]
`FUTURE`: generalize `~` to `/abs/path/to`. The change needs to be reflected in more than one place.

**Comment by tashrifbillah** [comment]
`~/` generalized with `/path/to` in:

pnlNipype: https://github.com/pnlbwh/pnlNipype/commit/ffecef0a8959403e4770bbea2d3d0292cf82ed47

pnlpipe: https://github.com/pnlbwh/pnlpipe/commit/a27d0ee7615e8870b3802b2ec5423259e821da85
