### ISSUE TITLE
DeGibbs and DeNoise

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/pnlNipype#7]
By Chris Rorden:

I would suggest adding de-Gibbs and de-noise to your pnlNipype pipeline:
  https://mrtrix.readthedocs.io/en/latest/reference/commands/mrdegibbs.html

 https://mrtrix.readthedocs.io/en/latest/reference/commands/dwidenoise.html

Just don't run de-Gibbs on partial-Fourier data (for Siemens images with a CSA header, look out for the "PartialFourier" tag in the BIDS header).

**Comment by tashrifbillah** [comment]
Both of them are being used in [dMRIharmonization](https://github.com/pnlbwh/dMRIharmonization)

**Comment by tashrifbillah** [comment]
https://github.com/dipy/dipy/issues/2054

**Comment by tashrifbillah** [comment]
Added [unring.py](https://github.com/pnlbwh/pnlNipype/blob/master/scripts/unring.py) module.

**Comment by tashrifbillah** [comment]
@neurolabusc

**Comment by AlbertoImg** [comment]
A double check question: 
Is there any step in the pnlNipype that performs denoising on DWI data? I could only see a unringing script for DeGibbs, but nothing for DeNoise. Is there any reason for avoiding denoising (if I did not miss such a script)? 
Thanks!
