### ISSUE TITLE
Typo in scripts overview

### ISSUE THREAD

**Issue by monicalyons** [pnlbwh/pnlNipype#8]
In https://github.com/pnlbwh/pnlNipype#pipeline-scripts-overview:
`fsl_toup_epi_eddy.py` should be `fsl_topup_epi_eddy.py`

**Comment by tashrifbillah** [comment]
https://github.com/pnlbwh/pnlNipype#2-install-pipeline

Fix the typo in pnlNipype

**Comment by tashrifbillah** [comment]
Fixed by https://github.com/pnlbwh/pnlNipype/commit/ab968386921d52f09ababf6dbd54e4eb1f296ee2
