### ISSUE TITLE
Missing output switch in example usage

### ISSUE THREAD

**Issue by monicalyons** [pnlbwh/pnlNipype#9]
In https://github.com/pnlbwh/pnlNipype/blob/master/TUTORIAL.md#freesurfer-segmentation-in-dwi-space: Examples are missing either -o or --outDir switch, but the documentation lists it as required.

**Comment by tashrifbillah** [comment]
Fixed by https://github.com/pnlbwh/pnlNipype/commit/ab968386921d52f09ababf6dbd54e4eb1f296ee2
