### ISSUE TITLE
Failed solving environment (gxx_linux-64 & gcc_linux-64)

### ISSUE THREAD

**Issue by melissadifabio** [pnlbwh/pnlNipype#94]
Hello,

I am getting an error while trying to install this pipeline with the step:
condo env create -f environment36.yml

The error reads:
Solving environment: Failed
ResolvePackageNotFound:
gxx_linux-64
gcc_linux-64

I am working from a Mac OS (miniconda platform: osx-64 - I do not have access to a Linux platform) and am unable to download those packages for osX. Is there anyway to solve this problem, or perhaps edit the environment36.yml to work for MacOS?

Thank you,
Melissa DiFabio

**Comment by tashrifbillah** [comment]
Hi Melissa, I haven't tested this on a MAC computer yet. How about editing the `environment36.yml` and removing them? If that does not work, feel free to Google to find their equivalent packages for MAC
