### ISSUE TITLE
tutorial-pnl has path to slicer version that is no longer there

### ISSUE THREAD

**Issue by RyanZurrin** [pnlbwh/pnlNipype#98]
/rfanfs/pnl-zorro/software/pnlpipe3/Slicer-4.8.4-linux-amd64/Slicer is a path referenced under the EPI Distortion Correction step of the tutorial and this is not there anymore. When trying to use the s10 version which contains all the modules, an error occurs: GSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.00ES, and 3.00 ES, and no images are able to be viewed. Not sure what slicer I am supposed to use on the network (Not Eris) that will allow me to complete the tutorial steps? Just figured I would ask here seems it is here where I am following the tutorial.

**Comment by tashrifbillah** [comment]
Communicated via Teams
